### ISSUE TITLE
why not include sources???

### ISSUE THREAD

**Issue by ebugfix** [jwvdiermen/grunt-include-source#31]
var appConfig = {
		app : 'src/app',
		dist : 'src/dist',
		tmp : 'src/.tmp',
		test : 'src/test',
	};

	// Define the configuration for all the tasks
	grunt.initConfig({
		// Project settings
		yeoman : appConfig, 

...ahead...

// grunt-include-source
		// Include your sources into your HTML files automatically.
		includeSource : {
			options : {
				basePath : '<%= yeoman.app %>',
				baseUrl : '/'
			},
			server : {
				files : {
					'<%= yeoman.tmp %>/index.html' : '<%= yeoman.app %>/index.html'
				}
			},
			dist : {
				files : {
					'<%= yeoman.dist %>/index.html' : '<%= yeoman.app %>/index.html'
				}
			}
		}
	});

html

**Comment by jwvdiermen** [comment]
Closing this for now since it's an old issue. If you still have issues, please give more details, since I've no idea what your issue is at the moment.
