### ISSUE TITLE
Include sources in the same file

### ISSUE THREAD

**Issue by gkaimakas** [jwvdiermen/grunt-include-source#32]
Currently when using grunt-include-source and specifying same input and output files in the output file the comments <-- include etc --> are removed and therefore I have to use a tmp file to do code.

Would it be difficult if the comments weren't deleted every time the script runs ?

**Comment by jwvdiermen** [comment]
Take a look at this part of the readme: https://github.com/jwvdiermen/grunt-include-source#overwriting-files

This should do what you are looking for.

**Comment by gkaimakas** [comment]
Thanks!!! I think that you should put it in the documentation
