### ISSUE TITLE
Includes duplicate JS files

### ISSUE THREAD

**Issue by akeelnazir** [jwvdiermen/grunt-include-source#34]
Globbing includes duplicates.

**Comment by jwvdiermen** [comment]
Can you please be more specific or give an example of the issue you're having which I can reproduce?

**Comment by edgar0011** [comment]
include in html source:






result html:

<script src="bower/angular/angular.js"></script>



<script src="bower/angular-animate/angular-animate.js"></script>
<script src="bower/angular-bootstrap/ui-bootstrap-tpls.js"></script>
<script src="bower/angular-cookies/angular-cookies.js"></script>
<script src="bower/angular-dynamic-locale/src/tmhDynamicLocale.js"></script>
<script src="bower/angular-local-storage/dist/angular-local-storage.js"></script>
<script src="bower/angular-resource/angular-resource.js"></script>
<script src="bower/angular-sanitize/angular-sanitize.js"></script>
<script src="bower/angular-translate-loader-partial/angular-translate-loader-partial.js"></script>
<script src="bower/angular-translate-storage-cookie/angular-translate-storage-cookie.js"></script>
<script src="bower/angular-translate-storage-local/angular-translate-storage-local.js"></script>
<script src="bower/angular-translate/angular-translate.js"></script>
<script src="bower/angular-ui-router/release/angular-ui-router.js"></script>
<script src="bower/angular/angular.js"></script>
<script src="bower/bootswatch-dist/js/bootstrap.js"></script>
<script src="bower/jquery/dist/jquery.js"></script>
<script src="bower/lodash/lodash.js"></script>

**Comment by edgar0011** [comment]
<script src="bower/angular/angular.js"></script>



<script src="bower/angular-animate/angular-animate.js"></script>
<script src="bower/angular-bootstrap/ui-bootstrap-tpls.js"></script>
<script src="bower/angular-cookies/angular-cookies.js"></script>
<script src="bower/angular-dynamic-locale/src/tmhDynamicLocale.js"></script>
<script src="bower/angular-local-storage/dist/angular-local-storage.js"></script>
<script src="bower/angular-resource/angular-resource.js"></script>
<script src="bower/angular-sanitize/angular-sanitize.js"></script>
<script src="bower/angular-translate-loader-partial/angular-translate-loader-partial.js"></script>
<script src="bower/angular-translate-storage-cookie/angular-translate-storage-cookie.js"></script>
<script src="bower/angular-translate-storage-local/angular-translate-storage-local.js"></script>
<script src="bower/angular-translate/angular-translate.js"></script>
<script src="bower/angular-ui-router/release/angular-ui-router.js"></script>
<script src="bower/angular/angular.js"></script>
<script src="bower/bootswatch-dist/js/bootstrap.js"></script>
<script src="bower/jquery/dist/jquery.js"></script>
<script src="bower/lodash/lodash.js"></script>

**Comment by edgar0011** [comment]
html source:
```html
<!-- include: "type": "js", "files": "bower/angular/**/*.js" -->
<!-- /include -->

<!-- include: "type": "js", "files": "bower/**/*.js" -->
<!-- /include -->
```


html result:
```html
<!-- include: "type": "js", "files": "bower/angular/**/*.js" -->
<script src="bower/angular/angular.js"></script>
<!-- /include -->

<!-- include: "type": "js", "files": "bower/**/*.js" -->
<script src="bower/angular-animate/angular-animate.js"></script>
<script src="bower/angular-bootstrap/ui-bootstrap-tpls.js"></script>
<script src="bower/angular-cookies/angular-cookies.js"></script>
<script src="bower/angular-dynamic-locale/src/tmhDynamicLocale.js"></script>
<script src="bower/angular-local-storage/dist/angular-local-storage.js"></script>
<script src="bower/angular-resource/angular-resource.js"></script>
<script src="bower/angular-sanitize/angular-sanitize.js"></script>
<script src="bower/angular-translate-loader-partial/angular-translate-loader-partial.js"></script>
<script src="bower/angular-translate-storage-cookie/angular-translate-storage-cookie.js"></script>
<script src="bower/angular-translate-storage-local/angular-translate-storage-local.js"></script>
<script src="bower/angular-translate/angular-translate.js"></script>
<script src="bower/angular-ui-router/release/angular-ui-router.js"></script>
<script src="bower/angular/angular.js"></script>
<script src="bower/bootswatch-dist/js/bootstrap.js"></script>
<script src="bower/jquery/dist/jquery.js"></script>
<script src="bower/lodash/lodash.js"></script>
<!-- /include -->
```


bower/angular/angular.js is duplicated

**Comment by jwvdiermen** [comment]
I see what you mean, but I'm not sure how this can be solved. Maybe by implementing a secondary pattern to exclude certain files:

```html
<!-- include: "type": "js", "files": "bower/angular/**/*.js" -->
<!-- /include -->

<!-- include: "type": "js", "files": "bower/**/*.js", "exclude": "bower/angular/**/*.js" -->
<!-- /include -->
```

What do you think? Shouldn't be difficult to implement.

**Comment by edgar0011** [comment]
Hi thanks for replying,

I think best would be if files would accept sort for comma delimited list of file patterns, so that exclusion could be achieved by exclamation mark:
"files": "bower//**/*.js, !bower/angular/**/*.js"

but what ever is easier, explicit exclude argument is also fine, but would have to accept list of patterns as well...IMHO

Thanks,

Martin

**Comment by bryanstrader** [comment]
The ability to exclude files would be great, and would help with the ordering issue as well (workaround).

**Comment by jwvdiermen** [comment]
This should now work as described in http://gruntjs.com/api/grunt.file#grunt.file.expand. See also https://github.com/jwvdiermen/grunt-include-source/blob/master/test/files/index.html#L69 for an example.

This is native for the pattern, but adding a `!` didn't work for me when using a comma separated list. So I manually split the `files` option before passing it to grunt's expand method.

Closing now, let me know if this doesn't work for you.

**Comment by genu** [comment]
Can you provide a more complete example of working with exclusions?

What do you mean by 
> So I manually split the files option before passing it to grunt's expand method.

How do you do that?
